production:
  :action_controller:
      :session:
        :secret:  hash_for_your_sessions
  :action_mailer:
      :delivery_method: :smtp
      :smtp_settings:
        :address: smtp.domain.com
        :port: 25
        :authentication: plain
        :user_name: username@domain.com
        :password: password
        :domain: domain.com
        :perform_deliveries: true
  :default_host: domain.com
  :bitly: bitly_api_key
  :google:
      :analytics_user_id: google_analytics_code
      :verification_code: google_webmaster_verification_code
      :custom_search_key: google_custom_search_code
  :cron_job_code: secret_key_to_access_the_cronjob
  :gateway:
      :login: login_to_payment_gateway
      :password: password_to_payment_gateway
  :recaptcha:
      :public_key: public_key
      :private_key: private_key
